# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PMit1t8fEIPM1YFcQ9-k1rE3upF_CEU
"""

print(int(4.9))
print(float(5))
print(str(10))
print(bool(0))
print(bool(1))