# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19As1i2frKqD9_lmJkF6J5HddeO3cpQtR
"""

name = "Prachi"
age = "17"
food = "Pizza"
print ("Hie",name,"you are",age,"years old","Your favourite food is",food)