# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzKBEe_Xv1UBhdAP2CapUklj5fF7MNWL
"""

a = "10"
b = int(a)
print (b+5)