# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8uCC2N9f01rdUHoQBMWnuu_kMk0Hvo8
"""

num1 = float(input("Enter first number"))
num2 = float(input("Enter second number"))

print("Sum:",num1+num2)
print("Difference",num1-num2)
print("Product",num1*num2)
print("Division",num1/num2)