# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XG-v0OeoyGwGD2tsKZE6hbwqF87ALDyt
"""

word = "Python"
print(word[0])
print(word[-1])
print (word[0:3])
print(len(word))
print(word.upper())
print(word.lower())
print(word.replace("P","C"))