# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kG8b9LgYsy9dwIl1pNuM4apwTTM0Iw-
"""

num= int(input("Enter your number"))
if num%2 == 0:
  print ("even")
else:
  print ("odd")