# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qpKCdqb-bbj5xPE8ebQIc4P9fFeNLAS
"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Hello",name,"you are",age,"years old")